//
//  PreguntaControler.swift
//  MutatioIOS
//
//  Created by user260925 on 7/22/24.
//

import Foundation
import UIKit

class PreguntaControler: UIViewController
{
    var pregunta: Pregunta?
    
    @IBOutlet weak var Titulo: UILabel!
    @IBOutlet weak var Texto: UITextView!
    
        override func viewDidLoad() {
        super.viewDidLoad()
            Titulo.text = pregunta?.ask ?? " "
            switch Titulo.text{
            case "¿La página https://cambiosinterestatales.sep.gob.mx\n es para Cambios dentro del mismo Estado?":
                Texto.text = "No, como su nombre lo indica es para Cambios y Permutas Interestatales o de Estado a Estado, los cambios al interno de los Estados son intraestatales y no se tiene participación ni injerencia en los mismos, ya que son facultad de las Secretarias de Educación de cada Estado."
            case "¿Hay diferencia entre el Proceso de Cambios \ny en el Proceso de Permutas de \nAdscripción de Estado a Estado?":
                Texto.text =            "Si, si ya cuentan con una persona con la cual llevar a cabo el movimiento, deberán registrarse en Permutas, si no tienen con quien permutar deben registrarse en Cambios, esa es la diferencia."
            case "¿El participar en los procesos \ngarantiza que mi cambio o permuta \nsea autorizado?":
                Texto.text =            "No, el hecho de participar en los Procesos no implica que el movimiento de cambio o permuta sea autorizado."
            case "¿En qué consiste el Proceso de Cambios de \nAdscripción de Estado a Estado?":
                Texto.text =            "La movilidad en este Proceso al igual que en el Proceso de permutas consiste en que, por un trabajador que salga de un Estado ingresara otro trabajador.\r\n\r\nEn este sentido, el Proceso de Cambios funciona con base al número de solicitudes que se reciben del personal interesado en algún cambio de Estado, y de ese modo, se llegue a generar el espacio que pueda ser ocupado por algún trabajador que solicite ingresar a ese Estado u otro y así sucesivamente, se van encadenando los movimientos; sin embargo, si no hay quien desee salir o ingresar a un Estado determinado, no existe la posibilidad de que pueda generarse algún movimiento.\r\n \r\nEstos movimientos (encadenamientos) se deben realizar en las mismas condiciones, como mismas categorías, niveles de carrera magisterial y demás cuestiones establecidas en la Convocatoria, dependiendo del nivel educativo que sé que trate, si no hay coincidencias entre Estados, categorías, niveles de carrera, estímulos y demás, no es posible se pueda autorizar algún movimiento.\r\n \r\nEs importante puntualizar que sabemos que el hecho de que participen en este Proceso es debido a que tienen alguna necesidad de cualquier índole y que por ello participan, sin embargo, este proceso depende del número de solicitudes que se reciban por Estado y nivel educativo, para que se pueda dar la movilidad.\r\n"
            case "¿En qué consiste el Proceso de Permutas de \nAdscripción de Estado a Estado?":
                Texto.text =            "Estas son concertadas de común acuerdo entre los trabajadores, manifestando su consentimiento por medio de la solicitud de permuta; estas son procedentes siempre y cuando los involucrados cumplan en su totalidad con los requisitos, reglas y fechas establecidas en la Convocatoria correspondiente. En este proceso los trabajadores deben encontrar con quien llevar a cabo la permuta, ya que es de común acuerdo entre las partes sin intervención de un tercero.\r\n \r\nLa no procedencia de una permuta se debe al incumplimiento en alguno de los requisitos, reglas o fechas establecidas en la Convocatoria.\r\n"
            case "¿Puedo elegir la ubicación en el Proceso de \nCambios o Permutas de Adscripción \nde Estado a Estado?":
                Texto.text =            "No, si se llega autorizar su movilidad en alguno de los Procesos, la ubicación la determinará su nuevo Estado de adscripción conforme a las necesidades del servicio y estructura ocupacional, para que verifiquen bien las Convocatorias, ya que en ellas se especifica esta situación.\n\nNota: Antes de participar en los Procesos de Cambios o Permutas, deben leer detenidamente la Convocatoria correspondiente en su totalidad."
            case  "¿Es posible que el sistema me registre en \nel proceso incorrecto, es decir, que inicie \nmi registro en cambios y me pase a permutas?":
                Texto.text =             "No, esto se debe a que antes de iniciar el registro se presentan dos cuadros de diálogo en donde el trabajador tiene que colocar que esta de acuerdo en iniciar el registro en el Proceso que el mismo seleccionó ya sea Cambios o Permuta."
            case "Me equivoqué en el registro, \nseleccioné incorrectamente Cambios cuando quiero \nsolicitar Permuta o viceversa, \n¿Qué puedo hacer para corregir?":
                Texto.text =            "Deberán solicitar la cancelación su registro actual por medio electrónico a la cuenta de correo: cambiosinter@nube.sep.gob.mx, con su nombre completo, RFC, número de solicitud a cancelar y motivo de cancelación (error al seleccionar proceso)."
            case "No tengo el número de solicitud ya que no concluí\n el registro, ¿Cómo lo obtengo?":
                Texto.text =            "Deberán realizar la misma acción, es decir, registrarse nuevamente y el Sistema le indicará que existe un RFC asociada a un número de solicitud y se lo mostrará."
            case "¿No encuentro mi categoría en el combo del nivel \neducativo en el que me registré?":
                Texto.text =            "Se están registrando en el nivel incorrecto, deben seguir la indicación que se les presenta al inicio del registro e ingresar al apartado de consulta tu nivel educativo, en donde deberán colocar en el recuadro la categoría que ostentan y una vez que se indique el resultado de la búsqueda deberán registrarse nuevamente en el nivel educativo al cual corresponde su categoría, que en ocasiones no es el nivel educativo donde laboran.\r\nO bien si se encuentran en el nivel educativo correcto deben buscar en todo el combo.\r\n"
            case "¿Cómo consulto o cómo sé cuál es mi categoría?":
                Texto.text =             "En el apartado de consulta tu nivel educativo, se muestra un ejemplo de la clave de cobro en donde se identifican los campos que componen dicha clave de cobro entre ellas la categoría (5 dígitos para docentes, 6 dígitos para personal de apoyo y asistencia a la educación)."
            case "Ya consulté mi categoría, revisando mi \ntalón de pago y el Sistema me indica que no se encontraron resultados, \n¿qué procede?":
                Texto.text =            "Deberá enviar un correo electrónico a cambiosinter@nube.sep.gob.mx informando la situación y recibirá respuesta de que procede en estos casos."
            case "No puedo imprimir, ya que me aparece que \nno tengo nombramientos registrados, ¿qué hago?":
                Texto.text =            "Deberá verificar el manual de usuario, ya que no registro correctamente el apartado de centro de trabajo o de nombramientos, una vez que verifique el manual o los videos de apoyo, deberá ingresar al apartado modificar solicitud con su RFC y número de solicitud, que debe colocar correctamente, para concluir el registro y continuar con las acciones correspondientes para su participación.\r\n\r\n"
            case "Descargué mi solicitud, pero está en blanco \n¿cómo lo soluciono?":
                Texto.text = "Se les recuerda lo establecido en el apartado de imprimir solicitud, donde se indica que para descargar correctamente su solicitud debe hacerlo por el explorador Firefox o bien Edge. \r\n\r\n\r\nPor lo anterior, deberá ingresar por cualquiera de estos dos exploradores para descargar correctamente su solicitud.\r\n"
            case "No ubico los datos para registrar mi unidad \ny subunidad, ¿Cómo o de dónde los obtengo?":
                Texto.text =            "Deberá ingresar al apartado de consulta tu nivel educativo, en donde viene un ejemplo de la clave de cobro, en donde se identifican los campos a registrar que, se verifican con del talón de pago en mano (Unidad, Subunidad, Categoría, Horas, Diagonal)."
            case "¿Participo en los Procesos de Cambios\n y Permutas de Adscripción de Estado a \nEstado solo con el registro?":
                Texto.text =             "No, deben verificar la Convocatoria en su totalidad, ya que en ella se indican los pasos a seguir para participar."
            case "¿Qué documentos debo anexar a mi solicitud?":
                Texto.text =             "Deben verificar la Convocatoria en su totalidad, ya que en ella se indica que documentos deben anexar en el apartado de requisitos para participar."
            case "¿En dónde entrego mi solicitud y documentos?":
                Texto.text =            "Tal y como se indica en la Convocatoria, podrán consultar las instancias facultadas en el área de recursos humanos de la Secretaría de Educación en su Estado de adscripción actual."
            case  "No me llega el correo de registro, \n¿Qué pasa en este caso, cómo lo obtengo?":
                Texto.text =            "El correo de notificación del registro, no tienen ninguna injerencia en los trámites que debe hacer para su participación, es como se indica solo es una notificación, que no se puede recuperar y se reitera no tienen injerencia en la participación, por lo que el recibirlo o no, no afecta."
            case "Deseo cancelar mi participación en el \nProceso de Cambios de Adscripción de Estado a Estado ¿Qué debo hacer?":
                Texto.text =            "1.\tSi solo tiene el registro y no ha hecho entrega de su solicitud o documentos.\r\n\r\nDebe enviar un correo a la cuenta: cambiosinter@nube.sep.gob.mx, con su nombre completo, RFC, número de solicitud a cancelar y motivo de cancelación; una vez que se confirme la recepción de esa información la cancelación se aplica en un lapso de tres a cinco días hábiles.\r\n\r\nSi los trabajadores quieren volver a realizar un registro, deberán estar al pendiente directamente en el Sistema en el tiempo antes mencionado para que verifiquen si ya pueden realizar un nuevo registro.\r\n\r\n2.\tSi ya hizo entrega de su solicitud y documentos en la instancia correspondiente en su Estado.\r\n\r\nTal y como se indica en la Convocatoria, debe solicitar la cancelación por escrito con los datos mínimos de: nombre completo, RFC, número de solicitud a cancelar y motivo de cancelación; el cual deberá entregarlo en la misma instancia en donde hizo entrega de su solicitud y documentos; posteriormente podrá enviar el acuse de dicho escrito a la cuenta: cambiosinter@nube.sep.gob.mx.\r\n\r\nUna vez que se confirme la recepción de su escrito, la cancelación se aplica en un lapso de tres a cinco días hábiles. \r\n\r\nSi los trabajadores quieren volver a realizar un registro, deberán estar al pendiente directamente en el Sistema en el tiempo antes mencionado para que verifiquen si ya pueden realizar un nuevo registro.\r\n"
            case"Deseo cancelar mi participación en el \nProceso de Permutas de Adscripción de Estado a \nEstado ¿Qué debo hacer?":
                Texto.text =             "1.\tSi solo tiene el registro y no ha asociado su solicitud ningún permutante.\r\n\r\nDebe enviar un correo a la cuenta: cambiosinter@nube.sep.gob.mx, con su nombre completo, RFC, número de solicitud a cancelar y motivo de cancelación; una vez que se confirme la recepción de esa información la cancelación se aplica en un lapso de tres a cinco días hábiles.\r\n\r\nSi los trabajadores quieren volver a realizar un registro, deberán estar al pendiente directamente en el Sistema en el tiempo antes mencionado para que verifiquen si ya pueden realizar un nuevo registro.\r\n\r\n2.\tSi ya solo tiene el registro, pero ya están asociadas las solicitudes con su o sus permutantes.\r\n\r\nDeberán todos los permutantes asociados al movimiento enviar un correo a la cuenta: cambiosinter@nube.sep.gob.mx, con su nombre completo, RFC, número de solicitud a cancelar y motivo de cancelación; una vez que se confirme la recepción de todas las peticiones de cancelación que integren la permuta, ésta se aplica en un lapso de tres a cinco días hábiles.\r\n\r\nSi los trabajadores quieren volver a realizar un registro, deberán estar al pendiente directamente en el Sistema en el tiempo antes mencionado para que verifiquen si ya pueden realizar un nuevo registro.\r\n\r\n3.\tSi los permutantes ya hicieron entrega de su solicitud y documentos en la instancia correspondiente en su Estado, o solo uno entregó y el otro u otros permutantes aún no lo hacen;  \r\n\r\nTal y como se indica en la Convocatoria, todos los permutantes deberán solicitar la cancelación por escrito con los datos mínimos de: nombre completo, RFC, número de solicitud a cancelar y motivo de cancelación.\r\n\r\nEl o los permutantes que hicieron entrega de solicitud y documentos deberán entregar sus escritos en la misma instancia en donde hicieron entrega de su solicitud y documentos; posteriormente podrá enviar el acuse de dicho escrito a la cuenta: cambiosinter@nube.sep.gob.mx.\r\n\r\nEl resto de los permutantes que no hubieran hecho de entrega de solicitud y documentos, solo deberán enviar su escrito a la cuenta de correo arriba mencionada y, una vez que se confirme la recepción de todos los escritos que integran la permuta, la cancelación se aplica en un lapso de tres a cinco días hábiles. \r\n\r\nSi los trabajadores quieren volver a realizar un registro, deberán estar al pendiente directamente en el Sistema en el tiempo antes mencionado para que verifiquen si ya pueden realizar un nuevo registro.\r\n"
            default:
                Titulo.text = "¡Advertencia!"
                Texto.text = "La siguiente información fue actualizada por ultima vez el 23/08/2024 en caso de que dude de la veracidad de esta información favor de comunicarse al cambiosinter@nube.sep.gob.mx"
            }
    }
}
